version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/srv/app
    networks:
      - appnet
    working_dir: /srv/app
  mariadb:
    image: mariadb:10.3
    ports:
      - "13306:3306"
    networks:
      - appnet
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myDBPW!isGrajt33
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
volumes:
  dbdata:
    driver: local
networks:
  appnet:
    driver: bridge


